name: Nentego Lodge 20
title: Nentego Lodge 20
logo: "/img/logo.png"
description: "Nentego Lodge serves as the chapter of Scouting’s National Honor Society for the Del-Mar-Va Council to serve our council's units, community, and camps."

# alert:
#   text: # (Here's a place you can put text for a site wide alert)
#   class: alert-primary # (Default is alert-primary)

plugins:
  - jekyll-paginate-v2
  - jekyll_picture_tag
  - jekyll/minibundle

url: http://127.0.0.1:4000
baseurl:

picture:
  nomarkdown: false

permalink: /news/:title

pagination:
  enabled: true
  per_page: 9
  permalink: '/:num/'
  title: 'News - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

page_gen:
  - data: 'chapters'
    template: 'chapters'
    name: 'chapter-name'
    dir: 'chapters'
