version: "3.8"
services:
  nginx: 
    container_name: nginx
    image: nginx:latest
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on: 
      - site
    ports:
      - 80:80
      - 443:443
    profiles:
      - prod
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    profiles:
      - prod
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  site:
    container_name: nentego
    image: nentego-site:latest
    build: ./
    ports:
    - 4000:4000
    expose:
    - "4000"
    volumes:
      - ${PWD}:/srv/jekyll
      - jekyll-cache:/usr/local/bundle
      - jekyll-gems:/usr/gem
    labels:
      - "jekyll"
volumes:
  jekyll-cache:
  jekyll-gems:
