name: Publish to Web
uses: appleboy/ssh-action@v0.1.3
env:
  DEVURL: ${{ secrets.DEVURL}}
  DEVDIR: ${{ secrets.DEVDIR }}
  PRODURL: ${{ secrets.PRODURL }}
  PRODDIR: ${{ secrets.PRODDIR }}

on:
  push:
    branches: [ development ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
