name: Publish to Web

on:
  push:
    branches: [ development ]

jobs:
  dev-deploy:
    name: Deploys Development Branch to Development Website
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVHOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEVKEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: whoami
