name: Publish to Web

on:
  push:
    branches: [ development ]

jobs:
  dev-deploy:
    name: Deploys Development Branch to Development Website
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        env:
          DEVURL: ${{ secrets.DEVURL}}
          DEVDIR: ${{ secrets.DEVDIR }}
          PRODURL: ${{ secrets.PRODURL }}
          PRODDIR: ${{ secrets.PRODDIR }}
        with:
          host: ${{ secrets.DEVHOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEVKEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd $DEVDIR
            git reset --hard
            git pull
